fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-tidy-imports, flake8-docstrings, flake8-rst-docstrings, flake8-comprehensions, flake8-bugbear, flake8-blind-except, flake8-builtins, flake8-pytest-style, flake8-mock, flake8-string-format]
