name: codecov 

on:
  push:
    branches:
      - master
      - publish
  pull_request:
    branches:
      - master
      - publish

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     pip install --upgrade pip
      #     pip install coverage
      # - name: Test
      #   run: |
      #     coverage run -m --source=eggplant unittest discover
      #     coverage xml
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
