name: codecov

on:
  push:
    branches:
      - master
      - publish
  pull_request:
    branches:
      - master
      - publish
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
