name: build

on:
  push:
    branches:
      - master
      - publish
  pull_request:
    branches:
      - master
      - publish

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          coverage run -m --source=eggplant unittest discover
          coverage xml
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
