steps:
- uses: actions/checkout@publish
- uses: codecov/codecov-action@v2
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ../coverage.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
